name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2020-05-14
        default: true
    - name: Build
      working-directory: domotics-backend
      run: cargo build --verbose
    - name: Run tests
      working-directory: domotics-backend
      run: cargo test --verbose
